payment:
    resource: "@PaymentBundle/Resources/config/routing.yml"
    prefix:   /

blog:
    resource: "@BlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"